# Profil production - PostgreSQL (app sur le host, DB dans Docker)
spring.datasource.url=jdbc:postgresql://db:5432/myrecipedb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=false
